In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print (arr1 + arr2)

[5 7 9]


In [3]:
menu = np.array(['cheese','bbq','veg','spicy'])
print(menu)

['cheese' 'bbq' 'veg' 'spicy']


In [6]:
prices = [100,200,150,220]
print(type(prices))
prices = np.array(prices) #conversion into numpy array
print(type(prices))
prices = prices * 0.8 #for 20% discount
print(prices)

<class 'list'>
<class 'numpy.ndarray'>
[ 80. 160. 120. 176.]


In [7]:
empty_table = np.zeros ((2,3)) #2 Rows, 3 Column
print(empty_table)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
full_table = np.ones ((2,3)) #2 Rows, 3 Column
print(full_table)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
bbq_box = np.full((2,3),'bbq')
print(bbq_box)

[['bbq' 'bbq' 'bbq']
 ['bbq' 'bbq' 'bbq']]


In [11]:
kids_order = np.random.randint(1,8, (2,3)) #randomly inserting values from 1 to 8 in 2*3 matrix
print(kids_order)

[[2 4 7]
 [1 4 3]]


In [12]:
surprise_topings = np.random.rand(2,3) #random float value between 0 to 1
print(surprise_topings) 

[[0.25744993 0.0623058  0.97716353]
 [0.40298106 0.65282597 0.14583513]]


In [19]:
signature_pizzas=np.identity(3)
print(signature_pizzas)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
delivery_times = np.arange(0,70,15)
print(delivery_times)

[ 0 15 30 45 60]


In [22]:
cooking_shifts = np.linspace(0,70,5) #0 to 70 range value ke 5 vag e devide kore.
print(cooking_shifts)

[ 0.  17.5 35.  52.5 70. ]


In [24]:
orders = np.array(['chese','veg','spicy','bbq'])
print(orders[2])

spicy


In [25]:
print(orders[:2]) #২ নাম্বার পজিশানের আগের পর্যন্ত জিনিসপত্র দেখাচ্ছে। 

['chese' 'veg']


In [32]:
orders = np.array([
    ['chese','veg','meat'],
    ['spicy','bbq','spicy']
])
print(orders[0,0])
print(orders[1,0])

chese
spicy


In [33]:
print(orders[:,1]) #Showing only column 1

['veg' 'bbq']


In [34]:
print(orders[:,0]) #Showing only column o

['chese' 'spicy']


In [35]:
print(orders[0,:])

['chese' 'veg' 'meat']


In [36]:
print(orders[0,1:3]) # ) Row 1 to 3 এর আগ পর্যন্ত কলাম। 

['veg' 'meat']


In [37]:
sales= np.array ([2000,1500,8000,3500])
print("Maximum Sales index", np.argmax(sales))
print("Max Sales",np.max(sales))

Maximum Sales index 2
Max Sales 8000


In [38]:
sales= np.array ([2000,1500,8000,3500])
print("Minimum Sales index", np.argmin(sales))
print("Min Sales",np.min(sales))

Minimum Sales index 1
Min Sales 1500
